export const COMMAND_BUS_REQUEST_MESSAGE = 'COMMAND_BUS_REQUEST_MESSAGE';
export const COMMAND_BUS_RESPONSE_MESSAGE = 'COMMAND_BUS_RESPONSE_MESSAGE';

export const POPUP_TO_WEBPAGE_MESSAGE = 'POPUP_TO_WEBPAGE_MESSAGE';

export const EXTENSION_SETTINGS_CHANGE = 'EXTENSION_SETTINGS_CHANGE';

export const GET_EXTENSION_SETTINGS_REQUEST = 'GET_EXTENSION_SETTINGS_REQUEST';
export const GET_EXTENSION_SETTINGS_RESPONSE =
  'GET_EXTENSION_SETTINGS_RESPONSE';
