export const GET_EXTENSION_SETTINGS_REQUEST = 'GET_EXTENSION_SETTINGS_REQUEST';
export const GET_EXTENSION_SETTINGS_RESPONSE =
  'GET_EXTENSION_SETTINGS_RESPONSE';

export const EXTENSION_POPUP_ROUTE = {
  HOME: '/',
  SETTINGS_HOME: '/settings',
  SETTINGS_CUSTOMIZATION: '/settings/customization',
};
