export const EXTENSION_SETTINGS_CHANGE = 'EXTENSION_SETTINGS_CHANGE';
export const GET_EXTENSION_SETTINGS_REQUEST = 'GET_EXTENSION_SETTINGS_REQUEST';
export const GET_EXTENSION_SETTINGS_RESPONSE =
  'GET_EXTENSION_SETTINGS_RESPONSE';

export const EXTENSION_POPUP_MENU_ROUTES = {
  HOME: '/',
  SETTINGS: {
    MAIN_VIEW: '/settings',
    CUSTOMIZATION: '/settings/customization',
  },
};
