export const EXTENSION_SETTINGS_CHANGE = 'EXTENSION_SETTINGS_CHANGE';
export const GET_EXTENSION_SETTINGS_REQUEST = 'GET_EXTENSION_SETTINGS_REQUEST';
export const GET_EXTENSION_SETTINGS_RESPONSE =
  'GET_EXTENSION_SETTINGS_RESPONSE';
