import { POLYMARKET_COMMAND_TO_HANDLER_MAP } from 'application/polymarket';
import { SNAPSHOT_COMMAND_TO_HANDLER_MAP } from 'application/snapshot';
import { MONITORING_COMMAND_TO_HANDLER_MAP } from 'shared/monitoring';

export const SERVICE_WORKER_COMMAND_HANDLERS_MAP = {
  ...SNAPSHOT_COMMAND_TO_HANDLER_MAP,
  ...POLYMARKET_COMMAND_TO_HANDLER_MAP,
  ...MONITORING_COMMAND_TO_HANDLER_MAP,
};
