export const COMMAND_BUS_REQUEST_MESSAGE = 'COMMAND_BUS_REQUEST_MESSAGE';
export const COMMAND_BUS_RESPONSE_MESSAGE = 'COMMAND_BUS_RESPONSE_MESSAGE';
export const POPUP_TO_WEBPAGE_MESSAGE = 'POPUP_TO_WEBPAGE_MESSAGE';
export const TOGGLE_EXTENSION_POPUP_VISIBILITY =
  'TOGGLE_EXTENSION_POPUP_VISIBILITY';
export const SWAP_EVENT = 'SWAP_EVENT';
