export { AavegotchiLogo } from './aavegotchi'
export { AcrossLogo } from './across'
export { GitcoinLogo } from './gitcoin'
export { ParallelLogo } from './parallel'
export { PolymarketLogo } from './polymarket'
export { TallyLogo } from './tally'