export const COMMAND_BUS_REQUEST_MESSAGE = 'COMMAND_BUS_REQUEST_MESSAGE';
export const COMMAND_BUS_RESPONSE_MESSAGE = 'COMMAND_BUS_RESPONSE_MESSAGE';
export const POPUP_TO_WEBPAGE_MESSAGE = 'POPUP_TO_WEBPAGE_MESSAGE';

export const SERVICE_WORKER_COMMAND_REQUEST = 'SERVICE_WORKER_COMMAND_REQUEST';
export const SERVICE_WORKER_COMMAND_RESPONSE =
  'SERVICE_WORKER_COMMAND_RESPONSE';
