export const COMMAND_BUS_REQUEST_MESSAGE = 'COMMAND_BUS_REQUEST_MESSAGE';
export const COMMAND_BUS_RESPONSE_MESSAGE = 'COMMAND_BUS_RESPONSE_MESSAGE';
export const POPUP_TO_WEBPAGE_MESSAGE = 'POPUP_TO_WEBPAGE_MESSAGE';
export const TOGGLE_EXTENSION_CONTEXT_MENU_VISIBILITY =
  'TOGGLE_EXTENSION_CONTEXT_MENU_VISIBILITY';
