name: CI

on:
  pull_request:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

  type-check:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      #  TODO: replace with turbo command like prepare or smth?
      - name: Build tailwind
        run: pnpm --filter=@idriss-xyz/extension build:tailwind

      #  TODO: replace with turbo command
      - name: Run type-check
        run: pnpm --filter=@idriss-xyz/extension type-check

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      #  TODO: replace with turbo command like prepare or smth?
      - name: Build tailwind
        run: pnpm --filter=@idriss-xyz/extension build:tailwind

      #  TODO: replace with turbo command
      - name: Run lint
        run: pnpm --filter=@idriss-xyz/extension lint

      #  TODO: replace with turbo command
      - name: Run format
        run: pnpm --filter=@idriss-xyz/extension format


  circular-deps:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      #  TODO: replace with turbo command like prepare or smth?
      - name: Build tailwind
        run: pnpm --filter=@idriss-xyz/extension build:tailwind

      #  TODO: replace with turbo command
      - name: Run circular dependencies check
        run: pnpm --filter=@idriss-xyz/extension circular-deps

  unused-exports:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      #  TODO: replace with turbo command
      - name: Run circular dependencies check
        run: pnpm --filter=@idriss-xyz/extension unused-exports
